### ISSUE TITLE
Is it possible to still show native horizontal tabs?

### ISSUE THREAD

**Issue by xerance** [drannex42/FirefoxSidebar#53]
I love the idea of auto hiding and extending the sidebar, but coming from regular sideberry i'm so used to using both native horizontal tabs and the sidemenu. 

Is it possible to keep the native horizontal tabs somehow?

**Comment by drannex42** [comment]
> I love the idea of auto hiding and extending the sidebar, but coming from regular sideberry i'm so used to using both native horizontal tabs and the sidemenu.

I don't quite agree with you, that just sounds like a visual nightmare, but if that's what you enjoy, having double options, go for it.  

You should eb able to just add this to your custom.css 

```css
#main-window #TabsToolbar {
  visibility: visible !important;
}
```
or
```css
#main-window #TabsToolbar {
  visibility: initial !important;
}
```

Haven't tested, but should work. Let me know.
